# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0002_auto_20180214_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='group',
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pollapp.Group'),
        ),
    ]
