# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0003_auto_20180214_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='desctription',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_closing',
            field=models.DateTimeField(null=True),
        ),
    ]
