# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0004_auto_20180214_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='desctription',
            new_name='description',
        ),
    ]
