# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0005_auto_20180214_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='description',
            new_name='instructions',
        ),
    ]
