# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0006_auto_20180214_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='users',
            new_name='user',
        ),
    ]
